# Generated by Django 2.2.5 on 2019-09-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='default-movie.png', upload_to='movie_posters'),
        ),
    ]
